language: python
python:
- '3.8'
install:
- pipenv install
script:
- python fpldraft.py -leagueID 3441 -teamName "randys11" -fantasyFootballScoutUsername $fantasyFootballScoutUsername -fantasyFootballScoutPassword $fantasyFootballScoutPassword
